### ISSUE TITLE
Mobile Versions

### ISSUE THREAD

**Issue by maltefiala** [Netzfreiheit/STI-UI#44]
Mobile versions currently under development.

- [x] [Android: Counter out of bounds](https://github.com/musha68k/STI-UI/issues/43 )
- [x] [Android Horizontal: No space on the left](https://github.com/musha68k/STI-UI/issues/42 )
- [x] [Android Vertical: Video swipe not working](https://github.com/musha68k/STI-UI/issues/38 )
- [x] [Android Vertical: Questionnaire space](https://github.com/musha68k/STI-UI/issues/37 )
- [x] [Android Vertical: Remove unnecessary width](https://github.com/musha68k/STI-UI/issues/36 )
- [x] [Android Vertical: Condense header to one line](https://github.com/musha68k/STI-UI/issues/35 )
